version: "3.4"  # Use version 3.4 or later to support health checks.

services:

  yada-node:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - restore
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/yadacoin
      - PYTHONUNBUFFERED=0
      - MOTOR_MAX_WORKERS=1
      - PYTHONPATH=/etc/yadacoin

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5

  restore:
    image: mongo:latest
    command: sh -c 'mongorestore --host mongodb /mongodump'
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - /etc/yadacoin/dump:/mongodump

volumes:
  mongodb_data:
