version: "3"

services:
  yada-node:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000" # Assuming the Tornado app runs on port 8000
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/yadacoin
      - PYTHONUNBUFFERED=0
      - MOTOR_MAX_WORKERS=1
      - PYTHONPATH=/etc/yadacoin

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - /etc/yadacoin/dump:/mongodump
      - ./mongo-init:/docker-entrypoint-initdb.d


volumes:
  mongodb_data:
