version: "3.4"

services:
  yada-node:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "8001:8001"
      - "3333:3333"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/yadacoin
      - PYTHONUNBUFFERED=0
      - MOTOR_MAX_WORKERS=1
      - PYTHONPATH=/etc/yadacoin
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"

  restore:
    image: mongo:latest
    command: sh -c 'mongorestore --host mongodb /mongodump > /dev/null 2>&1'
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - /etc/yadacoin/dump:/mongodump

  backup:
    image: mongo:latest
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - /etc/yadacoin:/etc/yadacoin
    command: sh -c 'mongodump --host mongodb --db=yadacoin --collection=blocks && tar -czvf /etc/yadacoin/bootstrap.tar.gz dump && mv /etc/yadacoin/bootstrap.tar.gz /etc/yadacoin/static/bootstrap.tar.gz'

volumes:
  mongodb_data:
