name: Build and Release

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8" # Adjust according to your project's needs

      - name: Install 7-Zip
        run: choco install 7zip -y

      - name: Install dependencies
        run: |
          grep -vE "pyrx" requirements.txt > filtered_requirements.txt
          python -m pip install --upgrade pip
          pip install -r filtered_requirements.txt
          pip install pyinstaller

      - name: Build with PyInstaller
        run: pyinstaller app.spec # or use the .spec file if you have one

      - name: Zip the contents of dist directory
        run: |
          cd dist
          7z a ../yadacoin-windows.zip ./*

      - name: Add README to the zip
        run: 7z u dist_contents.zip winlibs/pyrx.cp37-win_amd64.pyd

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./yadacoin-windows.zip
          asset_name: yadacoin-windows.zip
          asset_content_type: application/zip
