name: Release Test

on:
  release:
    types: [created, published, edited, prereleased]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a message
        run: echo "Release was created!"
